### ISSUE TITLE
Anchor Tag "Name" Attribute Stripped out when Allowed

### ISSUE THREAD

**Issue by kriskd** [burzum/cakephp-html-purifier#17]
If the name attribute of the anchor tag (example: `<a name="whatever"></a>`) is included in HTML.AllowedAttributes it is still stripped out.  I added this condition to the Test file and the test failed.

**Comment by burzum** [comment]
I don't think that's a problem of the plugin, the plugin is just a proxy. Can you test if that filter rule works with the Purifier lib itself?

**Comment by kriskd** [comment]
Thanks, a little reading of the HTML Purifier documentation and I think I have fixed it.  I simple had to add `'Attr.EnableID' => true` to my Purifier config and now the name attribute is maintained.
