### ISSUE TITLE
Plugin not loaded?

### ISSUE THREAD

**Issue by Perzonallica** [burzum/cakephp-html-purifier#27]
Hello!
I want to use the Helper, but I can't get it work. 

I added this line to the view:
`<?= $this->HtmlPurifier->clean($game->title, 'purifierBasicInputConfig') ?>`

Controller:
`public $helpers = [
        'Burzum/HtmlPurifier.HtmlPurifier' => [
            'config' => 'purifierBasicInputConfig'
        ]
    ];`

AppController:
`Purifier::config('purifierBasicInputConfig', array(
                'HTML.AllowedElements' => '',
                'Cache.SerializerPath' => ROOT . DS . 'tmp' . DS . 'purifier'
            )
        );`

Config:
`Plugin::load('Burzum/HtmlPurifier');`

When I open the view in the browser I get this:
_Error: HtmlPurifierHelper could not be found.
Error: Create the class HtmlPurifierHelper below in file: src\View\Helper\HtmlPurifierHelper.php_

Interesting is, that when I load it from one of my plugins it works, but on the base site it doesn't. Also when I load the plugin this way: [http://book.cakephp.org/3.0/en/views/helpers.html#configuring-helpers](book) it works. This works also, but I'm getting an error message too: [http://book.cakephp.org/3.0/en/views/helpers.html#loading-helpers-on-the-fly](book_2)
Am I missing something here?

I'm using the latest Cake version: 3.2.11

**Comment by burzum** [comment]
> Controller:
public $helpers = [ 'Burzum/HtmlPurifier.HtmlPurifier' => [ 'config' => 'purifierBasicInputConfig' ] ];

While this still works it's not the recommended way to load helpers. Helpers don't belong in the C layer of the MVC pattern and this has been addressed. It's only kept there for backward compatibility.

You should use the view instead: http://book.cakephp.org/3.0/en/views/helpers.html#loading-helpers-on-the-fly

I have no idea why it loads the helper in one of your plugins but not within the app. This is however a strong indicator that something with your app is wrong.

**Comment by Perzonallica** [comment]
OK, thanks for the info. I managed to solve this. I removed that line (public $helpers = [ '...) from the controllers and loaded the plugin from the AppView.php. Now it works everywhere.
