### ISSUE TITLE
Update to Cake4

### ISSUE THREAD

**Issue by LubosRemplik** [burzum/cakephp-html-purifier#32]
Is this still active plugin? Worth to update to Cake4?

**Comment by burzum** [comment]
@LubosRemplik I switched to Laravel but maintain the Cake plugins I've made as I need them for legacy projects or my company needs them. You have these options:

1) Do a PR. This is a very tiny warpper around the lib. It should be *very* easy to upgrade it. I'll accept a PR if it has tests and I'll tag a new major release.
2) Wait until my company needs Cake 4 if we're not ditching it in favour of something else.
3) Pay me to upgrade it (~1-2h?)

**Comment by burzum** [comment]
@LubosRemplik before I tag the version, can you please confirm that the **4.0** branch works for you without issues?

**Comment by LubosRemplik** [comment]
Hi @burzum unfortunatelly I can't confirm that, colleague did own behavior by himself to the project we needed.

**Comment by burzum** [comment]
@LubosRemplik the 4.0 branch *should* works, so you can use that branch. I'm not going to tag a release until I'm sure it works fine.

**Comment by burzum** [comment]
@netfly not that I'm aware of bump the version and make a PR. If it passes I'll accept it.

**Comment by burzum** [comment]
It's updated to CakePHP 4 if there are issues report them please.

Also if somebode else is interested in maintaining it please contact me. I'm no longer working with CakePHP. I prefer Laravel these days for my private projects and at work we're "frameworkless". I'm not very motivated to touch CakePHP related things for free in my spare time anymore.
